### ISSUE TITLE
rake aborted! cannot load such file -- zip/zip

### ISSUE THREAD

**Issue by rubyconvict** [kmmndr/geonames_dump#1]
I can't execute any take task.

Updating files in vendor/cache
- activerecord-reset-pk-sequence-0.2.0.gem
- ruby-progressbar-1.4.2.gem
- geonames_dump-0.0.2.gem
  Your bundle is complete!
  It was installed into ./vendor/bundle

$ bin/rails generate geonames_dump:install
      create  db/migrate/20140311085358_create_geonames_countries.rb
      create  db/migrate/20140311085359_create_geonames_features.rb
      create  app/models/geonames_admin1.rb
      create  app/models/geonames_admin2.rb
      create  app/models/geonames_city.rb
      create  app/models/geonames_country.rb
      create  app/models/geonames_feature.rb

$ bundle exec rake geonames_dump:install
rake aborted!
cannot load such file -- zip/zip

$ bundle exec rake -T | grep geonames_dump

rake aborted!
cannot load such file -- zip/zip

**Comment by kmmndr** [comment]
Hi Rubyconvict,
Rubyzip has been upgraded in version 0.0.6 of this gem.
Could you try using the latest version ?

**Comment by kmmndr** [comment]
I'm closing this as the latest version is fixed.
Feel free to re-open this issue if you encounter this bug using the latest version on rubygems.
